# Generated by Django 5.2.10 on 2026-02-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop_path',
            field=models.URLField(blank=True, help_text='TMDB backdrop path', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.URLField(blank=True, help_text='TMDB poster path', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, help_text='TMDB movie ID', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='TMDB vote average', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
    ]
