# Generated by Django 5.2.10 on 2026-02-02 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('popular', 'Popular'), ('trending', 'Trending'), ('personalized', 'Personalized'), ('similar', 'Similar Movies')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, help_text='Recommendation confidence score', max_digits=5)),
                ('reason', models.TextField(blank=True, help_text='Why this movie is recommended')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='movies.movie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'recommendation_type'], name='recommendat_user_id_b12654_idx'), models.Index(fields=['recommendation_type', 'score'], name='recommendat_recomme_80137d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('view', 'Viewed'), ('search', 'Searched'), ('rate', 'Rated'), ('comment', 'Commented'), ('add_to_watchlist', 'Added to Watchlist')], max_length=20)),
                ('metadata', models.JSONField(blank=True, help_text='Additional activity data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'activity_type'], name='recommendat_user_id_c1cdba_idx'), models.Index(fields=['activity_type', 'created_at'], name='recommendat_activit_77eec3_idx')],
            },
        ),
    ]
