# Generated by Django 5.2.10 on 2026-02-05 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_backdrop_path_movie_poster_path_movie_tmdb_id_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='movie_poster',
            field=models.URLField(blank=True, help_text='Movie poster URL cache', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='movie_title',
            field=models.CharField(blank=True, help_text='Movie title cache', max_length=200),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='tmdb_movie_id',
            field=models.IntegerField(blank=True, help_text='TMDB movie ID for movies not in local DB', null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='movies.movie'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(condition=models.Q(('movie__isnull', False)), fields=('user', 'movie'), name='unique_user_movie_watchlist'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(condition=models.Q(('tmdb_movie_id__isnull', False)), fields=('user', 'tmdb_movie_id'), name='unique_user_tmdb_movie_watchlist'),
        ),
    ]
